### ISSUE TITLE
Fix parseSvgText() for duotone layer ordering

### ISSUE THREAD

**Issue by mlwilkerson** [FortAwesome/fa-icon-chooser#38]
When implementing [`parseSvgText()`](https://github.com/FortAwesome/fa-icon-chooser/blob/c0fd599df0c18884952c1a1be22cd364b8676a7c/packages/fa-icon-chooser/src/utils/utils.ts#L69), I mistakenly thought that the primary layer appears before the secondary layer in the FA Standard SVGs. It's the other way: secondary first.

The parsing function and tests should be updated accordingly.

**Comment by Bibhavshah** [comment]
Can I work on this issue?

**Comment by mlwilkerson** [comment]
@Bibhavshah Of course! That would be great. To help with that, I've added [this commit](https://github.com/FortAwesome/fa-icon-chooser/commit/7cd85ead060c179a4dd1be4fca297bacf203ac2c) on a [new branch](https://github.com/FortAwesome/fa-icon-chooser/commits/parse-svg-text-test) that has revised tests that should all pass when `parseSvgText()` implementation is correct.

(You could cherry-pick that commit or just copy/paste the tests into your branch. We don't need necessarily need to keep that branch.)

**Comment by mlwilkerson** [comment]
I'm including a fix for this in #39. Turns out, the duotone icons were rendering visually correctly, because while `parseSvgText()` was getting the order backwards, the `fa-icon` component was _also_ doing it backwards. In this one case in the universe, two wrongs made it right.

#39 fixes both, which results in correctness, but no visual change in rendering.
