### ISSUE TITLE
I'd like to make an abstraction atop this for Microsoft's Blazor Web Assembly, where would you like it?

### ISSUE THREAD

**Issue by taylorchasewhite** [FortAwesome/fa-icon-chooser#42]
Hi Mike, I like this chooser, and I am planning to write a wrapper around the Javascript code for folks using Microsoft's Blazor WASM foundation. I currently manage BlazingApple and am thinking of doing it there, but if you'd like it to be within the FortAwesome org or this repo somewhere, I can do that too.

Let me know, thanks.

Taylor

**Comment by mlwilkerson** [comment]
Hi @taylorchasewhite. This is cool. I hadn't heard of Blazor before this. But it makes me wonder: if we produced components that were WASM instead of JavaScript, would that make them any more usable directly in a Blazor app?
